# .github/workflows/terraform.yml

name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Paso 3: Inicializar Terraform
      - name: Terraform Init
        run: terraform init
        env:
          TOKEN_COOPERATIVA: ${{ secrets.TOKEN_COOPERATIVA }}  # Usar el secreto de GitHub o el token
          KEY_PUBLIC_COOPERATIVA: ${{ secrets.KEY_PUBLIC_COOPERATIVA }}  # Usar la clave pública

      # Paso 4: Crear el plan de Terraform
      - name: Terraform Plan
        run: terraform plan
        env:
          TOKEN_COOPERATIVA: ${{ secrets.TOKEN_COOPERATIVA }}  # Usar el secreto de GitHub o el token
          KEY_PUBLIC_COOPERATIVA: ${{ secrets.KEY_PUBLIC_COOPERATIVA }}  # Usar la clave pública

      # Paso 5: Aplicar el plan de Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TOKEN_COOPERATIVA: ${{ secrets.TOKEN_COOPERATIVA }}  # Usar el secreto de GitHub o el token
          KEY_PUBLIC_COOPERATIVA: ${{ secrets.KEY_PUBLIC_COOPERATIVA }}  # Usar la clave pública
