name: Deploy Terraform to AWS

on:
  push:
    branches:
      - main 

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # Paso 3: Configurar las credenciales de AWS
      - name: Confirure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-acces-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-session-token: ${{ secrets.TOKEN_COOPERATIVA }}


      # Paso 5: Inicializar Terraform
      - name: Terraform Init
        run: terraform init

      # Paso 7: Aplicar el plan de Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve
