# .github/workflows/terraform.yml

name: Deploy Terraform to AWS

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # Paso 3: Configurar las credenciales de AWS desde los secretos de GitHub
      - name: Set AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" >> $GITHUB_ENV

      # Paso 4: Configurar el Token de GitHub para acceso a repositorios (si lo necesitas)
      - name: Set GitHub Token
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_COOPERATIVA }}
        run: |
          echo "GitHub Token set"

      # Paso 5: Inicializar Terraform
      - name: Terraform Init
        run: terraform init

      # Paso 6: Crear el plan de Terraform
      - name: Terraform Plan
        run: terraform plan

      # Paso 7: Aplicar el plan de Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve
